# Bulls räknas inte korrekt
# The number generated by the computer is 4162
# Guess four digits: 4444
# We got 1 cows
# We got 3 bulls

import random
import string

cows = 0 # Correct digit AND correct place
bulls = 0 # Correct digit NOT in correct place

def randomString(stringLength=4): # Generera lottonummer
    numbers = string.digits
    return ''.join(random.choice(numbers) for i in range(stringLength))

fourdigits = randomString(4)

print(f"\nThe number generated by the computer is {fourdigits}")

userguess = input("\nGuess four digits: ")

# Check first digit
if fourdigits[0] == userguess[0]: # Check cows
    cows = cows + 1
if fourdigits[0] != userguess[0]: # If not cow check bulls
        if userguess[0] in fourdigits:
            bulls = bulls +1

# Check second digit
if fourdigits[1] == userguess[1]:
    cows = cows + 1
if fourdigits[1] != userguess[1]:    # Stämmer inte om fourdigits[0] == userguess[0]
        if userguess[1] in fourdigits: # Unless it's a cow
            bulls = bulls +1

# Check third digit
if fourdigits[2] == userguess[2]:
    cows = cows + 1
if fourdigits[2] != userguess[2]:
        if userguess[2] in fourdigits:
            bulls = bulls +1

# Check fourth digit
if fourdigits[3] == userguess[3]:
    cows = cows + 1
if fourdigits[3] != userguess[3]:
        if userguess[3] in fourdigits:
            bulls = bulls +1

print(f"\nWe got {cows} cows")
print(f"We got {bulls} bulls")
