# Hur får man räkningen av cows och bulls att stämma. Ska man ha det i funktionen
# eller utanför

import random
import string

#cows = 0 # Correct digit AND correct place
#bulls = 0 # Correct digit NOT in correct place

def randomString(stringLength=4): # Generera lottonummer
    numbers = string.digits
    return ''.join(random.choice(numbers) for i in range(stringLength))

fourdigits = randomString(4)

print(f"\nThe number generated by the computer is {fourdigits}")

userguess = input("\nGuess four digits: ")

def digit_check(x, y):
    cows = 0
    bulls = 0
    if fourdigits[x] == userguess[y]: # Test for cows
        cows = cows + 1
    if fourdigits[x] != userguess[y]: # Test for bulls
            if userguess[x] in fourdigits:
                bulls = bulls +1
    print(cows)



digit_check(0, 0)
digit_check(1, 1)
