# Måste "cows" vara inne i funktionen


import random
import string

cows = 0 # Correct digit AND correct place
bulls = 0 # Correct digit NOT in correct place

def randomString(stringLength=4): # Generera lottonummer
    numbers = string.digits
    return ''.join(random.choice(numbers) for i in range(stringLength))

fourdigits = randomString(4)

print(f"\nThe number generated by the computer is {fourdigits}")

userguess = input("\nGuess four digits: ")

def digit_check(x, y):
    if fourdigits[x] == userguess[y]: # Test for cows
        cows = cows + 1
    if fourdigits[x] != userguess[y]: # Test for bulls
            if userguess[x] in fourdigits:
                bulls = bulls +1

digit_check(0, 0)

print(cows)
print(bulls)
